name: Build and Deploy Packages

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  PACKAGE_VER: 1.0.1-mx
  BUILD_TYPE: RelWithDebInfo
  NUGETTOKEN: ${{ secrets.NUGET_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use.
        source-url: https://nuget.pkg.github.com/MarcellvanRooyen/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GHPACKAGESTOKEN}}
    
    - name: Init git submodule
      # ensure that the libgit2 linkage is correct
      run: git submodule init

    - name: Update git submodule
      # updates the libgi2 linkage to the latest
      run: git submodule update
      
    - name: Build project
      # Build project using powershell script
      run: powershell .\build.libgit2.ps1
      run: powershell .\buildpackage_forMendix.ps1 -version $PACKAGE_VER
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/MarcellvanRooyen/index.json" -UserName MarcellVanRooyen -Password ${{ secrets.GITHUB_TOKEN }}
      run: nuget push **/*.nupkg -Source "GitHub" -SkipDuplicate
    
     
