name: Build and Deploy Packages

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .net
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/MarcellvanRooyen/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Init git submodule
      # ensure that the libgit2 linkage is correct
      run: git submodule init

    - name: Update git submodule
      # updates the libgi2 linkage to the latest
      run: git submodule update
      
    - name: Build project
      # Build project using powershell script
      run: powershell .\build.libgit2.ps1

    - name: Build Package
      # Package project into mendix package using powershell script
      run: powershell .\buildpackage_forMendix.ps1 -version 1.0.1-mx
      
    - name: Deploy Package
      # publish package to Github packages
      run: dotnet nuget push .\Mendix.LibGit2Sharp.NativeBinaries.1.0.1-mx.nupkg
